### ISSUE TITLE
Migrate the database & Start the server Error

### ISSUE THREAD

**Issue by makkopai** [TECHFUND/hiwrite#1]
I was facing the problem of not being able to install diesel_cli on M1Mac even though I tried [this issue](https://github.com/diesel-rs/diesel/issues/2605), but I solved it by installing Rust itself again with homebrew.
It seems that this was not a good thing that I had installed with rustup.

Then I faced another problem. It looks correct on the command line, but looks different from the capture in the README. 
Also, when I access localhost:8000, I get the following error on the command line,so please let me know how to deal with this.

```
❯ cargo run -- server 
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/hiwrite server`
Ran migrations.
HiWrite Up!
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: RenderError { desc: "Template not found: 404", template_name: None, line_no: None, column_no: None, cause: None }', src/page/controller/display.rs:19:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by nautical** [comment]
>diesel_cli on M1Mac

Ideal situation will be installing Rust with Homebrew and mentioning following in your local rust config

```
[target.aarch64-apple-darwin]
rustflags = '-L /opt/homebrew/opt/libpq/lib -L /opt/homebrew/lib'
```

>thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: RenderError { desc: "Template not found: 404", template_name: None, line_no: None, column_no: None, cause: None }', src/page/controller/display.rs:19:69

Most probably you were successful in running it and hitting an end point that is not handled , we should improve the error handling of unknown API endpoints.
